# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.10

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/feng/Distributed-Key-Value-Database

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/feng/Distributed-Key-Value-Database

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/feng/Distributed-Key-Value-Database/CMakeFiles /home/feng/Distributed-Key-Value-Database/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/feng/Distributed-Key-Value-Database/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named kvstore2pcsystem

# Build rule for target.
kvstore2pcsystem: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 kvstore2pcsystem
.PHONY : kvstore2pcsystem

# fast build rule for target.
kvstore2pcsystem/fast:
	$(MAKE) -f CMakeFiles/kvstore2pcsystem.dir/build.make CMakeFiles/kvstore2pcsystem.dir/build
.PHONY : kvstore2pcsystem/fast

src/conf.o: src/conf.cc.o

.PHONY : src/conf.o

# target to build an object file
src/conf.cc.o:
	$(MAKE) -f CMakeFiles/kvstore2pcsystem.dir/build.make CMakeFiles/kvstore2pcsystem.dir/src/conf.cc.o
.PHONY : src/conf.cc.o

src/conf.i: src/conf.cc.i

.PHONY : src/conf.i

# target to preprocess a source file
src/conf.cc.i:
	$(MAKE) -f CMakeFiles/kvstore2pcsystem.dir/build.make CMakeFiles/kvstore2pcsystem.dir/src/conf.cc.i
.PHONY : src/conf.cc.i

src/conf.s: src/conf.cc.s

.PHONY : src/conf.s

# target to generate assembly for a file
src/conf.cc.s:
	$(MAKE) -f CMakeFiles/kvstore2pcsystem.dir/build.make CMakeFiles/kvstore2pcsystem.dir/src/conf.cc.s
.PHONY : src/conf.cc.s

src/coordinator.o: src/coordinator.cc.o

.PHONY : src/coordinator.o

# target to build an object file
src/coordinator.cc.o:
	$(MAKE) -f CMakeFiles/kvstore2pcsystem.dir/build.make CMakeFiles/kvstore2pcsystem.dir/src/coordinator.cc.o
.PHONY : src/coordinator.cc.o

src/coordinator.i: src/coordinator.cc.i

.PHONY : src/coordinator.i

# target to preprocess a source file
src/coordinator.cc.i:
	$(MAKE) -f CMakeFiles/kvstore2pcsystem.dir/build.make CMakeFiles/kvstore2pcsystem.dir/src/coordinator.cc.i
.PHONY : src/coordinator.cc.i

src/coordinator.s: src/coordinator.cc.s

.PHONY : src/coordinator.s

# target to generate assembly for a file
src/coordinator.cc.s:
	$(MAKE) -f CMakeFiles/kvstore2pcsystem.dir/build.make CMakeFiles/kvstore2pcsystem.dir/src/coordinator.cc.s
.PHONY : src/coordinator.cc.s

src/kv.o: src/kv.cc.o

.PHONY : src/kv.o

# target to build an object file
src/kv.cc.o:
	$(MAKE) -f CMakeFiles/kvstore2pcsystem.dir/build.make CMakeFiles/kvstore2pcsystem.dir/src/kv.cc.o
.PHONY : src/kv.cc.o

src/kv.i: src/kv.cc.i

.PHONY : src/kv.i

# target to preprocess a source file
src/kv.cc.i:
	$(MAKE) -f CMakeFiles/kvstore2pcsystem.dir/build.make CMakeFiles/kvstore2pcsystem.dir/src/kv.cc.i
.PHONY : src/kv.cc.i

src/kv.s: src/kv.cc.s

.PHONY : src/kv.s

# target to generate assembly for a file
src/kv.cc.s:
	$(MAKE) -f CMakeFiles/kvstore2pcsystem.dir/build.make CMakeFiles/kvstore2pcsystem.dir/src/kv.cc.s
.PHONY : src/kv.cc.s

src/logger.o: src/logger.cc.o

.PHONY : src/logger.o

# target to build an object file
src/logger.cc.o:
	$(MAKE) -f CMakeFiles/kvstore2pcsystem.dir/build.make CMakeFiles/kvstore2pcsystem.dir/src/logger.cc.o
.PHONY : src/logger.cc.o

src/logger.i: src/logger.cc.i

.PHONY : src/logger.i

# target to preprocess a source file
src/logger.cc.i:
	$(MAKE) -f CMakeFiles/kvstore2pcsystem.dir/build.make CMakeFiles/kvstore2pcsystem.dir/src/logger.cc.i
.PHONY : src/logger.cc.i

src/logger.s: src/logger.cc.s

.PHONY : src/logger.s

# target to generate assembly for a file
src/logger.cc.s:
	$(MAKE) -f CMakeFiles/kvstore2pcsystem.dir/build.make CMakeFiles/kvstore2pcsystem.dir/src/logger.cc.s
.PHONY : src/logger.cc.s

src/main.o: src/main.cc.o

.PHONY : src/main.o

# target to build an object file
src/main.cc.o:
	$(MAKE) -f CMakeFiles/kvstore2pcsystem.dir/build.make CMakeFiles/kvstore2pcsystem.dir/src/main.cc.o
.PHONY : src/main.cc.o

src/main.i: src/main.cc.i

.PHONY : src/main.i

# target to preprocess a source file
src/main.cc.i:
	$(MAKE) -f CMakeFiles/kvstore2pcsystem.dir/build.make CMakeFiles/kvstore2pcsystem.dir/src/main.cc.i
.PHONY : src/main.cc.i

src/main.s: src/main.cc.s

.PHONY : src/main.s

# target to generate assembly for a file
src/main.cc.s:
	$(MAKE) -f CMakeFiles/kvstore2pcsystem.dir/build.make CMakeFiles/kvstore2pcsystem.dir/src/main.cc.s
.PHONY : src/main.cc.s

src/network.o: src/network.cc.o

.PHONY : src/network.o

# target to build an object file
src/network.cc.o:
	$(MAKE) -f CMakeFiles/kvstore2pcsystem.dir/build.make CMakeFiles/kvstore2pcsystem.dir/src/network.cc.o
.PHONY : src/network.cc.o

src/network.i: src/network.cc.i

.PHONY : src/network.i

# target to preprocess a source file
src/network.cc.i:
	$(MAKE) -f CMakeFiles/kvstore2pcsystem.dir/build.make CMakeFiles/kvstore2pcsystem.dir/src/network.cc.i
.PHONY : src/network.cc.i

src/network.s: src/network.cc.s

.PHONY : src/network.s

# target to generate assembly for a file
src/network.cc.s:
	$(MAKE) -f CMakeFiles/kvstore2pcsystem.dir/build.make CMakeFiles/kvstore2pcsystem.dir/src/network.cc.s
.PHONY : src/network.cc.s

src/parser.o: src/parser.cc.o

.PHONY : src/parser.o

# target to build an object file
src/parser.cc.o:
	$(MAKE) -f CMakeFiles/kvstore2pcsystem.dir/build.make CMakeFiles/kvstore2pcsystem.dir/src/parser.cc.o
.PHONY : src/parser.cc.o

src/parser.i: src/parser.cc.i

.PHONY : src/parser.i

# target to preprocess a source file
src/parser.cc.i:
	$(MAKE) -f CMakeFiles/kvstore2pcsystem.dir/build.make CMakeFiles/kvstore2pcsystem.dir/src/parser.cc.i
.PHONY : src/parser.cc.i

src/parser.s: src/parser.cc.s

.PHONY : src/parser.s

# target to generate assembly for a file
src/parser.cc.s:
	$(MAKE) -f CMakeFiles/kvstore2pcsystem.dir/build.make CMakeFiles/kvstore2pcsystem.dir/src/parser.cc.s
.PHONY : src/parser.cc.s

src/participant.o: src/participant.cc.o

.PHONY : src/participant.o

# target to build an object file
src/participant.cc.o:
	$(MAKE) -f CMakeFiles/kvstore2pcsystem.dir/build.make CMakeFiles/kvstore2pcsystem.dir/src/participant.cc.o
.PHONY : src/participant.cc.o

src/participant.i: src/participant.cc.i

.PHONY : src/participant.i

# target to preprocess a source file
src/participant.cc.i:
	$(MAKE) -f CMakeFiles/kvstore2pcsystem.dir/build.make CMakeFiles/kvstore2pcsystem.dir/src/participant.cc.i
.PHONY : src/participant.cc.i

src/participant.s: src/participant.cc.s

.PHONY : src/participant.s

# target to generate assembly for a file
src/participant.cc.s:
	$(MAKE) -f CMakeFiles/kvstore2pcsystem.dir/build.make CMakeFiles/kvstore2pcsystem.dir/src/participant.cc.s
.PHONY : src/participant.cc.s

src/test/kv_test.o: src/test/kv_test.cc.o

.PHONY : src/test/kv_test.o

# target to build an object file
src/test/kv_test.cc.o:
	$(MAKE) -f CMakeFiles/kvstore2pcsystem.dir/build.make CMakeFiles/kvstore2pcsystem.dir/src/test/kv_test.cc.o
.PHONY : src/test/kv_test.cc.o

src/test/kv_test.i: src/test/kv_test.cc.i

.PHONY : src/test/kv_test.i

# target to preprocess a source file
src/test/kv_test.cc.i:
	$(MAKE) -f CMakeFiles/kvstore2pcsystem.dir/build.make CMakeFiles/kvstore2pcsystem.dir/src/test/kv_test.cc.i
.PHONY : src/test/kv_test.cc.i

src/test/kv_test.s: src/test/kv_test.cc.s

.PHONY : src/test/kv_test.s

# target to generate assembly for a file
src/test/kv_test.cc.s:
	$(MAKE) -f CMakeFiles/kvstore2pcsystem.dir/build.make CMakeFiles/kvstore2pcsystem.dir/src/test/kv_test.cc.s
.PHONY : src/test/kv_test.cc.s

src/test/logger_test.o: src/test/logger_test.cc.o

.PHONY : src/test/logger_test.o

# target to build an object file
src/test/logger_test.cc.o:
	$(MAKE) -f CMakeFiles/kvstore2pcsystem.dir/build.make CMakeFiles/kvstore2pcsystem.dir/src/test/logger_test.cc.o
.PHONY : src/test/logger_test.cc.o

src/test/logger_test.i: src/test/logger_test.cc.i

.PHONY : src/test/logger_test.i

# target to preprocess a source file
src/test/logger_test.cc.i:
	$(MAKE) -f CMakeFiles/kvstore2pcsystem.dir/build.make CMakeFiles/kvstore2pcsystem.dir/src/test/logger_test.cc.i
.PHONY : src/test/logger_test.cc.i

src/test/logger_test.s: src/test/logger_test.cc.s

.PHONY : src/test/logger_test.s

# target to generate assembly for a file
src/test/logger_test.cc.s:
	$(MAKE) -f CMakeFiles/kvstore2pcsystem.dir/build.make CMakeFiles/kvstore2pcsystem.dir/src/test/logger_test.cc.s
.PHONY : src/test/logger_test.cc.s

src/test/network_test.o: src/test/network_test.cc.o

.PHONY : src/test/network_test.o

# target to build an object file
src/test/network_test.cc.o:
	$(MAKE) -f CMakeFiles/kvstore2pcsystem.dir/build.make CMakeFiles/kvstore2pcsystem.dir/src/test/network_test.cc.o
.PHONY : src/test/network_test.cc.o

src/test/network_test.i: src/test/network_test.cc.i

.PHONY : src/test/network_test.i

# target to preprocess a source file
src/test/network_test.cc.i:
	$(MAKE) -f CMakeFiles/kvstore2pcsystem.dir/build.make CMakeFiles/kvstore2pcsystem.dir/src/test/network_test.cc.i
.PHONY : src/test/network_test.cc.i

src/test/network_test.s: src/test/network_test.cc.s

.PHONY : src/test/network_test.s

# target to generate assembly for a file
src/test/network_test.cc.s:
	$(MAKE) -f CMakeFiles/kvstore2pcsystem.dir/build.make CMakeFiles/kvstore2pcsystem.dir/src/test/network_test.cc.s
.PHONY : src/test/network_test.cc.s

src/test/parser_test.o: src/test/parser_test.cc.o

.PHONY : src/test/parser_test.o

# target to build an object file
src/test/parser_test.cc.o:
	$(MAKE) -f CMakeFiles/kvstore2pcsystem.dir/build.make CMakeFiles/kvstore2pcsystem.dir/src/test/parser_test.cc.o
.PHONY : src/test/parser_test.cc.o

src/test/parser_test.i: src/test/parser_test.cc.i

.PHONY : src/test/parser_test.i

# target to preprocess a source file
src/test/parser_test.cc.i:
	$(MAKE) -f CMakeFiles/kvstore2pcsystem.dir/build.make CMakeFiles/kvstore2pcsystem.dir/src/test/parser_test.cc.i
.PHONY : src/test/parser_test.cc.i

src/test/parser_test.s: src/test/parser_test.cc.s

.PHONY : src/test/parser_test.s

# target to generate assembly for a file
src/test/parser_test.cc.s:
	$(MAKE) -f CMakeFiles/kvstore2pcsystem.dir/build.make CMakeFiles/kvstore2pcsystem.dir/src/test/parser_test.cc.s
.PHONY : src/test/parser_test.cc.s

src/third_party/ossSocket/ossSocket.o: src/third_party/ossSocket/ossSocket.cc.o

.PHONY : src/third_party/ossSocket/ossSocket.o

# target to build an object file
src/third_party/ossSocket/ossSocket.cc.o:
	$(MAKE) -f CMakeFiles/kvstore2pcsystem.dir/build.make CMakeFiles/kvstore2pcsystem.dir/src/third_party/ossSocket/ossSocket.cc.o
.PHONY : src/third_party/ossSocket/ossSocket.cc.o

src/third_party/ossSocket/ossSocket.i: src/third_party/ossSocket/ossSocket.cc.i

.PHONY : src/third_party/ossSocket/ossSocket.i

# target to preprocess a source file
src/third_party/ossSocket/ossSocket.cc.i:
	$(MAKE) -f CMakeFiles/kvstore2pcsystem.dir/build.make CMakeFiles/kvstore2pcsystem.dir/src/third_party/ossSocket/ossSocket.cc.i
.PHONY : src/third_party/ossSocket/ossSocket.cc.i

src/third_party/ossSocket/ossSocket.s: src/third_party/ossSocket/ossSocket.cc.s

.PHONY : src/third_party/ossSocket/ossSocket.s

# target to generate assembly for a file
src/third_party/ossSocket/ossSocket.cc.s:
	$(MAKE) -f CMakeFiles/kvstore2pcsystem.dir/build.make CMakeFiles/kvstore2pcsystem.dir/src/third_party/ossSocket/ossSocket.cc.s
.PHONY : src/third_party/ossSocket/ossSocket.cc.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... kvstore2pcsystem"
	@echo "... edit_cache"
	@echo "... src/conf.o"
	@echo "... src/conf.i"
	@echo "... src/conf.s"
	@echo "... src/coordinator.o"
	@echo "... src/coordinator.i"
	@echo "... src/coordinator.s"
	@echo "... src/kv.o"
	@echo "... src/kv.i"
	@echo "... src/kv.s"
	@echo "... src/logger.o"
	@echo "... src/logger.i"
	@echo "... src/logger.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/network.o"
	@echo "... src/network.i"
	@echo "... src/network.s"
	@echo "... src/parser.o"
	@echo "... src/parser.i"
	@echo "... src/parser.s"
	@echo "... src/participant.o"
	@echo "... src/participant.i"
	@echo "... src/participant.s"
	@echo "... src/test/kv_test.o"
	@echo "... src/test/kv_test.i"
	@echo "... src/test/kv_test.s"
	@echo "... src/test/logger_test.o"
	@echo "... src/test/logger_test.i"
	@echo "... src/test/logger_test.s"
	@echo "... src/test/network_test.o"
	@echo "... src/test/network_test.i"
	@echo "... src/test/network_test.s"
	@echo "... src/test/parser_test.o"
	@echo "... src/test/parser_test.i"
	@echo "... src/test/parser_test.s"
	@echo "... src/third_party/ossSocket/ossSocket.o"
	@echo "... src/third_party/ossSocket/ossSocket.i"
	@echo "... src/third_party/ossSocket/ossSocket.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

